In [1]:
import pandas as pd

data = pd.read_csv('data.csv')

In [2]:
data.head()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0

In [5]:
data.columns

Index(['StudentID', 'Age', 'Gender', 'Ethnicity', 'ParentalEducation',
       'StudyTimeWeekly', 'Absences', 'Tutoring', 'ParentalSupport',
       'Extracurricular', 'Sports', 'Music', 'Volunteering', 'GPA',
       'GradeClass'],
      dtype='object')

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          2392 non-null   int64
 1   Age                2392 non-null   int64
 2   Gender             2392 non-null   int64
 3   Ethnicity          2392 non-null   int64
 4   ParentalEducation  2392 non-null   int64
 5   StudyTimeWeekly    2392 non-null   float64
 6   Absences           2392 non-null   int64
 7   Tutoring           2392 non-null   int64
 8   ParentalSupport    2392 non-null   int64
 9   Extracurricular    2392 non-null   int64
 10  Sports             2392 non-null   int64
 11  Music              2392 non-null   int64
 12  Volunteering       2392 non-null   int64
 13  GPA                2392 non-null   float64
 14  GradeClass         2392 non-null   float64
dtypes: float64(3), int64(12)
memory usage: 280.4 KB

In [7]:
data.describe()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
count,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000
mean,2196.500000,16.468645,0.510870,0.877508,1.746237,9.771992,14.541388,0.301421,2.122074,0.383361,0.303512,0.196906,0.157191,1.906186,2.983696
std,690.655244,1.123798,0.499986,1.028476,1.000411,5.652774,8.467417,0.458971,1.122813,0.486307,0.459870,0.397744,0.364057,0.915156,1.233908
min,1001.000000,15.000000,0.000000,0.000000,0.000000,0.001057,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1598.750000,15.000000,0.000000,0.000000,1.000000,5.043079,7.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.174803,2.000000
50%,2196.500000,16.000000,1.000000,0.000000,2.000000,9.705363,15.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,1.893393,4.000000
75%,2794.250000,17.000000,1.000000,2.000000,2.000000,14.408410,22.000000,1.000000,3.000000,1.000000,1.000000,0.000000,0.000000,2.622216,4.000000
max,3392.000000,18.000000,1.000000,3.000000,4.000000,19.978094,29.000000,1.000000,4.000000,1.000000,1.000000,1.000000,1.000000,4.000000,4.000000

In [8]:
data = data.drop(columns='StudentID')

In [9]:
data.head()

,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0

In [11]:
data.isna().sum()

Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

In [12]:
data.duplicated().sum()

np.int64(0)

In [13]:
data.head()

,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0

In [14]:
data['GradeClass'] = data['GPA'].apply(
    lambda x: 'A' if x > 3.5 else
              'B' if 3.0 < x <= 3.5 else
              'C' if 2.5 < x <= 3.0 else
              'D' if 2.0 < x <= 2.5 else
              'E'
)

In [15]:
data.head()

,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,C
1,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,B
2,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,E
3,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,D
4,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,E

In [16]:
data['ParentalSupport'].unique()

array([2, 1, 3, 4, 0])

In [17]:
Y = data['GradeClass']
X = data.drop(columns= 'GradeClass')

In [18]:
X.head()

,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA
0,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196
1,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915
2,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602
3,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218
4,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061

In [19]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.3,
    random_state=42,
    stratify=Y  # Recommended for classification
)

In [24]:
Y_train.unique()

array(['E', 'C', 'D', 'B', 'A'], dtype=object)

In [25]:
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [27]:
scaler = StandardScaler()

In [ ]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [28]:
from sklearn.ensemble import RandomForestClassifier

In [30]:
model = RandomForestClassifier(
    n_estimators=1000,
    random_state=42
)

In [31]:
model.fit(X_train, Y_train)

RandomForestClassifier(n_estimators=1000, random_state=42)

In [32]:
Y_pred = model.predict(X_test)

In [34]:
print("Accuracy:", accuracy_score(Y_test, Y_pred)*100)

print("\nClassification Report")
print(classification_report(Y_test, Y_pred))

print("\nConfusion Matrix")
print(confusion_matrix(Y_test, Y_pred))

Accuracy: 98.46796657381616

Classification Report
              precision    recall  f1-score   support

           A       1.00      0.74      0.85        23
           B       0.92      0.96      0.94        73
           C       0.97      0.99      0.98       116
           D       0.98      1.00      0.99       124
           E       1.00      1.00      1.00       382

    accuracy                           0.98       718
   macro avg       0.98      0.94      0.95       718
weighted avg       0.99      0.98      0.98       718


Confusion Matrix
[[ 17   6   0   0   0]
 [  0  70   3   0   0]
 [  0   0 115   1   0]
 [  0   0   0 124   0]
 [  0   0   0   1 381]]

In [40]:
Y.head()

0    C
1    B
2    E
3    D
4    E
Name: GradeClass, dtype: object

In [42]:
X.columns

Index(['Age', 'Gender', 'Ethnicity', 'ParentalEducation', 'StudyTimeWeekly',
       'Absences', 'Tutoring', 'ParentalSupport', 'Extracurricular', 'Sports',
       'Music', 'Volunteering', 'GPA'],
      dtype='object')

In [44]:
data = pd.read_csv('data.csv')

In [45]:
data.head()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0

In [46]:
data = data.drop(columns='StudentID')

In [47]:
data['GradeClass'] = data['GPA'].apply(
    lambda x: 'A' if x > 3.5 else
              'B' if 3.0 < x <= 3.5 else
              'C' if 2.5 < x <= 3.0 else
              'D' if 2.0 < x <= 2.5 else
              'E'
)

In [49]:
data = data.drop(columns='GPA')

In [50]:
data.head()

,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GradeClass
0,17,1,0,2,19.833723,7,1,2,0,0,1,0,C
1,18,0,0,1,15.408756,0,0,1,0,0,0,0,B
2,15,0,2,3,4.210570,26,0,2,0,0,0,0,E
3,17,1,0,3,10.028829,14,0,3,1,0,0,0,D
4,17,1,0,2,4.672495,17,1,3,0,0,0,0,E

In [51]:
Y = data['GradeClass']
X = data.drop(columns='GradeClass')

In [52]:
from sklearn.model_selection import train_test_split

In [54]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.3,
    random_state=42,
    stratify=Y  
)

In [55]:
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [56]:
scaler = StandardScaler()

In [57]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [58]:
from sklearn.ensemble import RandomForestClassifier

In [71]:
model = RandomForestClassifier(
    n_estimators=10000,
    random_state=42
)

In [72]:
model.fit(X_train, Y_train)

RandomForestClassifier(n_estimators=10000, random_state=42)

In [73]:
Y_pred = model.predict(X_test)

In [74]:
print("Accuracy:", accuracy_score(Y_test, Y_pred)*100)

print("\nClassification Report")
print(classification_report(Y_test, Y_pred))

print("\nConfusion Matrix")
print(confusion_matrix(Y_test, Y_pred))

Accuracy: 76.18384401114207

Classification Report
              precision    recall  f1-score   support

           A       0.50      0.26      0.34        23
           B       0.57      0.52      0.54        73
           C       0.57      0.66      0.61       116
           D       0.57      0.57      0.57       124
           E       0.93      0.93      0.93       382

    accuracy                           0.76       718
   macro avg       0.63      0.59      0.60       718
weighted avg       0.76      0.76      0.76       718


Confusion Matrix
[[  6  16   1   0   0]
 [  5  38  29   1   0]
 [  1  13  76  26   0]
 [  0   0  27  71  26]
 [  0   0   0  26 356]]

In [75]:
from sklearn.metrics import classification_report

print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           A       0.50      0.26      0.34        23
           B       0.57      0.52      0.54        73
           C       0.57      0.66      0.61       116
           D       0.57      0.57      0.57       124
           E       0.93      0.93      0.93       382

    accuracy                           0.76       718
   macro avg       0.63      0.59      0.60       718
weighted avg       0.76      0.76      0.76       718

In [76]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)

param_dist = {
    'n_estimators': [10000, 20000, 30000, 5000],
    'max_depth': [10, 20, 30, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'class_weight': [None, 'balanced']
}

random = RandomizedSearchCV(
    estimator=model,
    param_distributions=param_dist,
    n_iter=20,
    cv=5,
    scoring='f1_weighted',
    random_state=42,
    n_jobs=-1
)

random.fit(X_train, Y_train)

print(random.best_params_)

{'n_estimators': 10000, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_depth': None, 'class_weight': 'balanced'}

In [79]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# Prediction
y_pred = random.best_estimator_.predict(X_test)

# Metrics
print("Accuracy :", accuracy_score(Y_test, y_pred))
print("Precision:", precision_score(Y_test, y_pred, average='weighted'))
print("Recall   :", recall_score(Y_test, y_pred, average='weighted'))
print("F1 Score :", f1_score(Y_test, y_pred, average='weighted'))

print("\nClassification Report")
print(classification_report(Y_test, y_pred))

print("\nConfusion Matrix")
print(confusion_matrix(Y_test, y_pred))

Accuracy : 0.7785515320334262
Precision: 0.7859498989206137
Recall   : 0.7785515320334262
F1 Score : 0.7813455036356494

Classification Report
              precision    recall  f1-score   support

           A       0.53      0.39      0.45        23
           B       0.64      0.67      0.65        73
           C       0.64      0.66      0.65       116
           D       0.56      0.62      0.59       124
           E       0.95      0.91      0.93       382

    accuracy                           0.78       718
   macro avg       0.66      0.65      0.65       718
weighted avg       0.79      0.78      0.78       718


Confusion Matrix
[[  9  13   1   0   0]
 [  8  49  15   1   0]
 [  0  15  77  24   0]
 [  0   0  28  77  19]
 [  0   0   0  35 347]]

In [95]:
import joblib

best_model = random.best_estimator_

joblib.dump(best_model, "student_model.pkl")

['student_model.pkl']

In [96]:
import joblib

model = joblib.load("student_model.pkl")

In [97]:
import numpy as np

new_student = np.array([[18,1,2,3,12.5,4,1,3,1,0,1,0]])

new_student = scaler.transform(new_student)   # only if you trained with scaling

prediction = model.predict(new_student)

print(prediction)

c:\Users\aadit\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

['B']

In [ ]:
import matplotlib.pyplot as plt